# Generated by Django 2.2.5 on 2019-10-21 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bday',
            field=models.DateField(default=datetime.date(2019, 10, 21)),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='pass', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='uname',
            field=models.CharField(default='uname', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
